owner: softcreatr
repo: statuspage
user-agent: Status Check
sites:
  - name: 1-2.dev
    url: https://1-2.dev
  - name: SoftCreatR Media
    url: https://www.softcreatr.com/health-check
status-website:
  cname: is.softcreatr.online
  logoUrl: /icon.svg
  name: Status / Uptime
